-- cruiz@cican.net Concepción Ruiz Marín   Usuario 
-- copias@cican.net    copias  Usuario 
-- famuedo@cican.net   Francisco Amuedo Monge  Usuario 
-- iperez@cican.net    Inmacula Perez Ruiz Usuario 
-- jgalan@cican.net    Joaquín Galán Márquez   Usuario 
-- jcgarcia@cican.net  Juan Carlos García Caro Usuario 
-- jfigueroa@cican.net Juan Miguel Figueroa Yañez  Usuario 
-- mruiz@cican.net Mª. del Mar Ruiz Begines Usuario 
-- mggonzalez@cican.net    Mª. Gracia González Rodríguez    Usuario 
-- mdominguez@cican.net    Manuel Domínguez Mora   Usuario 
-- mfernandez@cican.net    María Eugenia Fernández Mayal   Usuario 
-- prueba@cican.net    prueba  Usuario 
-- postgres@cican.net  Superusuario PostgreSQL Usuario 
-- vhbenito@cican.net  Víctor Hugo Benito Villalba Usuario 
INSERT INTO usuario VALUES(1, 
                           NULL, 
                           'admin', 
                           'cee9be15784861e244ca2e58268343c8',
                           'Francisco José Rodríguez Bogado',
                           'frbogado@grupogea21.com',
                           '',
                           0,
                           'frbogado@novaweb.es',
                           'gea21.es', 
                           'frbogado@grupogea21.com', 
                           '', 
                           TRUE, 
                           TRUE, 
                           TRUE, 
                           TRUE, 
                           TRUE, 
                           'Administrador de la aplicación');

INSERT INTO usuario VALUES(2, 
                           NULL, 
                           'cruiz', 
                           '1a404787e2e59679397416189145f6f8',
                           'Concepción Ruiz Marín',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'cruiz@cican.net',
                           'gea21.es', 
                           'cruiz@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(3, 
                           NULL, 
                           'famuedo', 
                           '1ab0ca8d9675eaf738d72f59145a37c9',
                           'Francisco Amuedo Monge',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'famuedo@cican.net',
                           'gea21.es', 
                           'famuedo@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(4, 
                           NULL, 
                           'iperez', 
                           '22d3680515aaeb02ac9bf47b64db4aac',
                           'Inmacula Pérez Ruiz',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'iperez@cican.net',
                           'gea21.es', 
                           'iperez@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(5, 
                           NULL, 
                           'jgalan', 
                           '78a65add3aef24e0e2f2d34b2c1265ad',
                           'Joaquín Galán Márquez',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'jgalan@cican.net',
                           'gea21.es', 
                           'jgalan@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(6, 
                           NULL, 
                           'jcgarcia', 
                           '26d46aa786b6eb9042820691ec93cee9',
                           'Juan Carlos García Caro',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'jcgarcia@cican.net',
                           'gea21.es', 
                           'jcgarcia@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(7, 
                           NULL, 
                           'jfigueroa', 
                           'd4d70fd56c6e0f5033123e251d648a38',
                           'Juan Miguel Figueroa Yáñez',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'jfigueroa@cican.net',
                           'gea21.es', 
                           'jfigueroa@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(8, 
                           NULL, 
                           'mruiz', 
                           '867341f5ac5254c39bed76cc26e8490a',
                           'Mª. del Mar Ruiz Begines',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'mruiz@cican.net',
                           'gea21.es', 
                           'mruiz@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(9, 
                           NULL, 
                           'mggonzalez', 
                           '5ef5d4a5baa4820ab392024c90c085ae',
                           'Mª. Gracia González Rodríguez',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'mggonzalez@cican.net',
                           'gea21.es', 
                           'mggonzalez@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(10, 
                           NULL, 
                           'mdominguez', 
                           '22095922a82d3b0a55c8d31b4de7e23a',
                           'Manuel Domínguez Mora',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'mdominguez@cican.net',
                           'gea21.es', 
                           'mdominguez@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(11, 
                           NULL, 
                           'mfernandez', 
                           'bc3b03752471f39d94ad3a8d9ae70706',
                           'María Eugenia Fernández Mayal',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'mfernandez@cican.net',
                           'gea21.es', 
                           'mfernandez@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
INSERT INTO usuario VALUES(12, 
                           NULL, 
                           'vhbenito', 
                           '5bdc5044d0c9c58a7bbd6ba60f3b748a',
                           'Víctor Hugo Benito Villalba',
                           'nw_cican@grupogea21.com',
                           '',
                           5,
                           'vhbenito@cican.net',
                           'gea21.es', 
                           'vhbenito@grupogea21.com', 
                           '', 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           FALSE, 
                           'Creado automáticamente con contraseña por defecto igual a su nombre de usuario.');
